### ISSUE TITLE
Crash on shutdown

### ISSUE THREAD

**Issue by zooba** [micahmo/obs-progress#1]
Hi, I saw your "known issue" in the README about the crash on shutdown, and I think I know what at least one cause is. Didn't see anything open here to comment on, so I opened a new one.

At https://github.com/micahmo/obs-progress/blob/master/src/obs-progress.cpp#L148 you're releasing the object keeping the current scene alive, which means that now OBS itself has the only active handle to it (possibly other plugins too, but let's assume they're handling this properly already). During shutdown, this handle is released, and so the memory backing it all is freed.

However, because your timer is still firing, it comes in and assumes that the pointers in `_sources` are still valid. Since this isn't true, it crashes.

I assume the same thing could happen if you change scene collection while running, though _maybe_ you'll get the notification of the new scene before the deallocation happens and will get away with it ;)

If this were my codebase, I'd stick the `currentSceneSource` value into a variable alongside `_sources` and only release it after you are clearing `_sources`. Then you'll want to stop the timer and clear everything during `obs_module_unload`. I'm 99% sure the timer can't trigger after modules are unloaded, but if `_sources` is empty then it shouldn't matter if it does.

Hopefully that's helpful! I'm not set up for developing OBS or plugins or I'd throw together a PR for you, but if you need me to I can try and get set up for it. My outside-of-work contribution time is pretty slim these days though, but I do appreciate your plugin!

**Comment by micahmo** [comment]
Hi @zooba! Thanks for checking out the plugin and opening this issue. I really appreciate the info.

I guess this issue depends on two things...
1. The order of operations when OBS shuts down
2. When the memory for the sources is released

The original idea was to call `obs_frontend_get_current_scene` to get the Source representation of the current scene. Then, since I know it's a scene-type source, I turn around and call `obs_scene_from_source` to get the Scene representation. At this point, I figured I was done with the scene's Source object, so I released it.

It sounds like you're suggesting...
1. OBS releases source memory before unloading plugin modules
2. When OBS releases the scene source (which it does because I no longer have a handle to it), it also frees the source's scenes
3. Sometime after this, my progress timer tries to access the sources, which are no longer valid pointers
4. In theory, if I keep the handle to the current scene's Source object, it won't get freed (at least not until after the plugin is unloaded), so my timer won't be accessing an invalid pointer

I tried something along the lines of what you're suggesting, but I'm still seeing the crash on shutdown. Do you want to look at the changes and see if it's close to what you had in mind? Here's the commit: 9aeb5f6f304451d209da1d06af3b2653f19811a5

Also here is the stack from the crash dump if you can gather any additional insight. Something is happening when it tries to release the scene items.

```
w32-pthreads.dll!pthread_mutex_lock+0x35
obs.dll!getsignal_locked+0x40
obs.dll!signal_handler_disconnect+0x3c
obs.dll!obs_sceneitem_destroy+0xac
obs.dll!obs_sceneitem_release+0x43
obs.dll!remove_all_items+0xd3
obs.dll!scene_destroy+0x32
obs.dll!obs_source_destroy+0x1c2
obs.dll!obs_free_data+0x77
obs.dll!obs_shutdown+0x434
obs64.exe!OBSContext::~OBSContext+0x23
obs64.exe!OBSApp::~OBSApp+0xd5
obs64.exe!run_program+0x874
obs64.exe!main+0x6bf
obs64.exe!WinMain+0xed
obs64.exe!invoke_main+0x32
obs64.exe!__scrt_common_main_seh+0x12e
obs64.exe!__scrt_common_main+0xe
obs64.exe!WinMainCRTStartup+0x9
kernel32.dll!0x7ff8407c6fd4
ntdll.dll!0x7ff84193cec1
```

P.S. If you do want to set up for OBS development and contribute, that would be awesome!

**Comment by zooba** [comment]
Had a look at the PR and spotted one thing that may cause this, so hopefully that's it.

Sorry I forgot to check back in until OBS crashed on me again :D I think this can also occur when you remove a video source while it's playing, but it seems likely to be the same issue (removing the source decrements its reference count to zero so it gets released, even though obs-progress still has an uncounted reference).

**Comment by micahmo** [comment]
Thanks for the comments, I'm all ears on this issue! Still getting a shutdown exception after implementing your suggestion. Feel free to take a look at the updated PR.

**Comment by micahmo** [comment]
See PR #3 for resolution.
